version: '3'

services:

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000

  event:
    build:
      context: .
    environment:
      - DB_ADDRESS=root:password@tcp(mysql:3306)/localdb?charset=utf8&parseTime=True&loc=Local
      - DB_DEBUG=true
      - DB_AUTO_MIGRATE=true
    restart: always
    ports:
      - 19000:19000
    networks:
      - appnet

  mysql:
    image: mysql:5.7
#    volumes:
#      - ./mysql/init:/docker-entrypoint-initdb.d
#      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=N
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=hoge
      - MYSQL_DATABASE=localdb
    ports:
      - 3306:3306
    networks:
      - appnet

volumes:
  portainer-data:
    driver: local

networks:
  appnet:
    driver: bridge